version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-legenda-flipper
    restart: unless-stopped
    environment:
      - PORT=3000
      - NODE_PATH=/src
      - NODE_ENV=container
      - LEGENDA_USER=fliperapp
      - LEGENDA_PASS=123456
      - LEGENDA_URL=http://legendas.tv
    depends_on:
      - mysql
    ports:
      - 3000:3000
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
    volumes:
      - ./src:/app/src
    command: npm run devMigration
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-legenda-flipper
    environment:
      MYSQL_ROOT_PASSWORD: "fliper"
      MYSQL_DATABASE: "crawler"
      MYSQL_USER: "fliper"
      MYSQL_PASSWORD: "fliper"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
